version: '3'

services:
  lion-app:
    depends_on:
      - db
    container_name: lion-app-test
    build: #이미지 대신 빌드해서
      context: lion_app
      dockerfile: Dockerfile
    command: /start
    env_file:
      - ./.envs/local/django
      - ./.envs/local/db
      - ./.envs/local/server

  db:
    container_name: db-test
    image: postgres:15
    env_file:
      - ./.envs/local/db
    ports:
      - 54322:5432

volumes:
  staticfiles: