name: CI

on:
    pull_request:

    push:
        branches:
            - 'master'

env:
    IMAGE: ${{ secrets.NCR_REGISTRY }}/lion-app
    IMAGE_TAG: ${{ secrets.NCR_REGISTRY }}/lion-app:latest

jobs:
    lint:
      name: Check lint(black)
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'
        - name: install black
          run: pip install black
        - name: check black
          run: black --check lion_app

    build:
        name: Build Image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ secrets.NCR_REGISTRY }}
                username: ${{ secrets.NCR_ACCESS_KEY_ID }}
                password: ${{ secrets.NCR_SECRET_KEY }}
            - name: Get Current Timestamp
              id: timestamp
              run: echo "timestamp=$(date '+%s')" >> "$GITHUB_OUTPUT"

            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                context: lion_app
                tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ steps.timestamp.outputs.timestamp }}"
                push: false