name: lesson1

on:
  push:
  pull_request:

jobs:
    echo-event:
        name: echo event
        runs-on: ubuntu-latest 

        steps:
        - name: Get Event
          run: echo "This event is ${{github.event_name}}"
        - name: echo github context
          run: echo "url:${{github.repositoryUrl}}"


    docker-build:
        name: docker build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: build
              working-directory: lion_app
              run: |
                docker build --tag lion-app .

    docker-images:
        if: ${{always()}}
        needs: docker-build
        name: docker images
        runs-on: ubuntu-latest
        steps:
            - name: docker images
              run: docker images lion-app