name: lesson1

on:
  push:
  pull_request:

jobs:
    echo-event:
        name: echo event
        runs-on: ubuntu-latest 

        steps:
        - name: Get Event
          run: echo "This event is ${{github.event_name}}"
        - name: echo github context
          run: echo "url:${{github.repositoryUrl}}"


    docker-compose-build:
        name: docker compose build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: list files
              run: ls -al
            - name: run docker-compose-build
              run: docker-compose build