name: CD using Docker Image

on:
    push:
        branches:
            - 'master'

jobs:
    # 빌드 이미지 / NCR에 이미지 push
    build-and-push:
        name: actions/checkout@v3
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and Export
              uses: docker/build-push-action@v4
              with:
                context: lion_app
                tags: likelion-cr-jh.kr.ncr.ntruss.com/lion-app:latest
                push: true
            