name: lesson1

on:
  push:
  pull_request:

jobs:
    echo-event:
        name: echo event
        runs-on: ubuntu-latest 

        steps:
        - name: Get Event
          run: echo "This event is ${{github.event_name}}"
        - name: echo github context
          run: echo "url:${{github.repositoryUrl}}"


    docker-build:
        name: docker build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build Lion Image
              run: |
                cd lion_app
                docker build --tag lion-app